export const GET_CINEMA_REQUEST = "GET_CINEMA_REQUEST"
export const GET_CINEMA_SUCCESS = "GET_CINEMA_SUCCESS"
export const GET_CINEMA_FAILURE = "GET_CINEMA_FAILURE"

export const GET_CUMRAPBY_CINEMAS_REQUEST = "GET_CUMRAPBY_CINEMAS_REQUEST"
export const GET_CUMRAPBY_CINEMAS_SUCCESS = "GET_CUMRAPBY_CINEMAS_SUCCESS"
export const GET_CUMRAPBY_CINEMAS_FAILURE = "GET_CUMRAPBY_CINEMAS_FAILURE"

export const GET_SHOWTIMESBY_CINEMAS_REQUEST = "GET_SHOWTIMESBY_CINEMAS_REQUEST"
export const GET_SHOWTIMESBY_CINEMAS_SUCCESS = "GET_SHOWTIMESBY_CINEMAS_SUCCESS"
export const GET_SHOWTIMESBY_CINEMAS_FAILURE = "GET_SHOWTIMESBY_CINEMAS_FAILURE"
