export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"


export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const LOGOUT_REQUEST = "LOGOUT_REQUEST"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAILURE = "LOGOUT_FAILURE"

export const GET_USER_HISTORY_REQUEST = "GET_USER_HISTORY_REQUEST"
export const GET_USER_HISTORY_SUCCESS = "GET_USER_HISTORY_SUCCESS"
export const GET_USER_HISTORY_FAILURE = "GET_USER_HISTORY_FAILURE"

export const UPDATE_AT_USER_REQUEST = "UPDATE_AT_USER_REQUEST"
export const UPDATE_AT_USER_SUCCESS = "UPDATE_AT_USER_SUCCESS"
export const UPDATE_AT_USER_FAILURE = "UPDATE_AT_USER_FAILURE"

export const GET_INFO_USER_REQUEST = "GET_INFO_USER_REQUEST"
export const GET_INFO_USER_SUCCESS = "GET_INFO_USER_SUCCESS"
export const GET_INFO_USER_FAILURE = "GET_INFO_USER_FAILURE"

