export const GET_BOOKING_REQUEST = "GET_BOOKING_REQUEST";
export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
export const GET_BOOKING_FAILURE = "GET_BOOKING_FAILURE";

export const DAT_GHE_REQUEST = "DAT_GHE_REQUEST";
export const DAT_GHE_SUCCESS = "DAT_GHE_SUCCESS";
export const DAT_GHE_FAILURE = "DAT_GHE_FAILURE";

export const DAT_VE_REQUEST = "DAT_VE_REQUEST";
export const DAT_VE_SUCCESS = "DAT_VE_SUCCESS";
export const DAT_VE_FAILURE = "DAT_VE_FAILURE";

export const ADD_SHOWTIMES_REQUEST = "ADD_SHOWTIMES_REQUEST";
export const ADD_SHOWTIMES_SUCCESS = "ADD_SHOWTIMES_SUCCESS";
export const ADD_SHOWTIMES_FAILURE = "ADD_SHOWTIMES_FAILURE";
