export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST"
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS"
export const GET_MOVIE_FAILURE = "GET_MOVIE_FAILURE"

export const GET_MOVIE_PAG_REQUEST = "GET_MOVIE_PAG_REQUEST"
export const GET_MOVIE_PAG_SUCCESS = "GET_MOVIE_PAG_SUCCESS"
export const GET_MOVIE_PAG_FAILURE = "GET_MOVIE_PAG_FAILURE"

export const GET_MOVIE_SEARCH_REQUEST = "GET_MOVIE_SEARCH_REQUEST"
export const GET_MOVIE_SEARCH_SUCCESS = "GET_MOVIE_SEARCH_SUCCESS"
export const GET_MOVIE_SEARCH_FAILURE = "GET_MOVIE_SEARCH_FAILURE"

