export const GET_MOVIE_REQUEST = "GET_MOVIE_REQUEST"
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS"
export const GET_MOVIE_FAILURE = "GET_MOVIE_FAILURE"

export const GET_MOVIE_PAG_REQUEST = "GET_MOVIE_PAG_REQUEST"
export const GET_MOVIE_PAG_SUCCESS = "GET_MOVIE_PAG_SUCCESS"
export const GET_MOVIE_PAG_FAILURE = "GET_MOVIE_PAG_FAILURE"

export const GET_MOVIE_SEARCH_REQUEST = "GET_MOVIE_SEARCH_REQUEST"
export const GET_MOVIE_SEARCH_SUCCESS = "GET_MOVIE_SEARCH_SUCCESS"
export const GET_MOVIE_SEARCH_FAILURE = "GET_MOVIE_SEARCH_FAILURE"

export const ADD_MOVIE_REQUEST = "ADD_MOVIE_REQUEST"
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS"
export const ADD_MOVIE_FAILURE = "ADD_MOVIE_FAILURE"

export const DELETE_MOVIE_REQUEST = "DELETE_MOVIE_REQUEST"
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS"
export const DELETE_MOVIE_FAILURE = "DELETE_MOVIE_FAILURE"

export const UPDATE_MOVIE_REQUEST = "UPDATE_MOVIE_REQUEST"
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS"
export const UPDATE_MOVIE_FAILURE = "UPDATE_MOVIE_FAILURE"
